# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8d57a516704701a55b753198785d433e6e0a54e52fc145580b59ac42a9d7243145abfa918206583cdfd1cf7ecdc7cc4e09cd07b9de744a773de198dbb72ede

test:
  secret_key_base: 986d65b426afce1cc63c5b53c981e497676a6811a27ca3bbff4df16e68e97f5f903403a23a88c8c952e8d8d5a8a6c673d600ecea9d5c245c0fed84ead5b00869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
